name: tailwind
description: "A simple Tailwind utility library for Flutter, enabling quick and efficient UI building with utility-first classes, making it easier to create clean and responsive designs."
version: 0.0.2
publish_to: pub.dev
homepage: https://github.com/codingmitra/tailwind
repository: https://github.com/codingmitra/tailwind
issue_tracker: https://github.com/codingmitra/tailwind/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

funding:
  - https://buymeacoffee.com/hirokbanik

topics:
  - tailwind
  - colors
  - utilities
  - widget